const provincesDescription =[
    {
        provinceName:"Kampong Thom Travel",
        description:"Kampong Thom is Cambodia's second largest province by area. Its capital is named Kampong Thom, a picturesque town on the banks of the Stung Saen River.The Sambor temple and Prei Kuk temple are the two main temples in Kompong Thom as well as other less significant Angkorian sites. Kompong Thom was a very powerful capital in Southeast Asia during the Funan period. Later on, during the French rule, the province was home to a large group named the Stieng, but they have long been assimilated into Khmer society.Kampong Pos Thom was the original name of the present called Kampong Thom. Because originally long time ago, at the dock of the Sen River next to a big natural lake, there was a big cave with a pair of big snakes inside. The people living around this area usually saw these big snakes every Buddhist Holiday.",
    },
]

const blogCardItem = [

    {
        id: 1,
        cardBlog:"/image/kampong thom/Prasat Yeah Puon/p6.jpg",
        cardDetail1:"/image/kampong thom/Prasat Yeah Puon/pic1.jpg",
        cardDetail2:"/image/kampong thom/Prasat Yeah Puon/pic2.jpg",
        cardDetail3:"/image/kampong thom/Prasat Yeah Puon/pic3.jpg",
        cardDetail4:"/image/kampong thom/Prasat Yeah Puon/pic4.jpg",
        cardDetail5:"/image/kampong thom/Prasat Yeah Puon/pic5.jpg",
        Title:"Prasat Yeah Puon ",
        map:"https://mapcarta.com/W391642136",
        description1:"Prasat Yeah Puon Group comprised a total of 22 sanctuaries (5 have octagonal shapes) with two wall rampart, and was built of brick, masonry, laterite and sandstone in rectangular from in 7th century (600-635) during the reign of Isanavarman I to dedicated to Shiva. They were built on a hill with Gopura from the eastern and western entrances joining to an outside laterite rampart. The inner rampart reached by gateways from the four directions and joined to the brick rampart carved in various clustering figures.",
        description2:"This is the main attraction in and around Kampot. Unfortunately at the time of writing it is largely closed to visitors as the road is being repaired. Bokor hill station was built by the French as a high-altitude complement to the fashionable seaside resort of Kep across the bay. Both are now faded and crumbling in a very atmospheric fashion. Bokor was also the scene of fierce fighting in the '80s, with Khmer Rouge and Vietnamese troops battling it out across the mountaintop for control of the buildings and the rest of this strategic area of high ground.",
        howTogo:"7 km away from the mountain, sits a swimming spot at Popork Vil Waterfall. Tourists can swim and bathe here for pleasure.",
    },
    {
        id:2,
        cardBlog:"/image/kampong thom/Prey Pros/Prey Pros.jpg",
        cardDetail1:"/image/kampong thom/Prey Pros/pic1.jpg",
        cardDetail2:"/image/kampong thom/Prey Pros/pic2.jpg",
        cardDetail3:"/image/kampong thom/Prey Pros/pic3.jpg",
        cardDetail4:"/image/kampong thom/Prey Pros/pic4.jpg",
        cardDetail5:"/image/kampong thom/Prey Pros/pic5.jpg",
        Title:"Prey Pros",
        map:"https://www.google.com/search?q=map+from+phnom+penh+to+Prey+Pros&biw=1280&bih=569&sxsrf=ALiCzsZ6AUjOomyp6GUsV0FroSUnMitE_A%3A1671549897394&ei=ydOhY7XCF6erseMPhd6pqAU&ved=0ahUKEwj1yu7OwIj8AhWnVWwGHQVvClUQ4dUDCA8&uact=5&oq=map+from+phnom+penh+to+Prey+Pros&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAE6CggAEEcQ1gQQsAM6BAgjECc6BggAEBYQHjoFCAAQhgNKBAhBGABKBAhGGABQwANY_AdgsRNoAXABeACAAXaIAcYBkgEDMS4xmAEAoAEBoAECyAECwAEB&sclient=gws-wiz-serp#",
        description1:"Prey Pros is a natural and cultural site located at Prey Pros Village, Prey Preal Commune, Kampong Svay District in approximate 16-km distance northwest of Kampong Thom province. The site cover an area of 2 million square meters and includes a river which is rich in Domrei fish. The site is a venue for foot races, bicycle races, and other games during national festivals. In addition, there are several recreational activities such as boating, fishing and swimming, with resting cottage where food and drinks are sold. The view from Prey Pros is beautiful and enchanting, with wind blowing across the river cooling and refreshing visitors.",
        description2:"This is the main attraction in and around Kampot. Unfortunately at the time of writing it is largely closed to visitors as the road is being repaired. Bokor hill station was built by the French as a high-altitude complement to the fashionable seaside resort of Kep across the bay. Both are now faded and crumbling in a very atmospheric fashion. Bokor was also the scene of fierce fighting in the '80s, with Khmer Rouge and Vietnamese troops battling it out across the mountaintop for control of the buildings and the rest of this strategic area of high ground.",
        howTogo:"7 km away from the mountain, sits a swimming spot at Popork Vil Waterfall. Tourists can swim and bathe here for pleasure.",
    },
    {
        id:3,
        cardBlog:"/image/kampong thom/Phnom Santuk/Phnom Santuk.jpg",
        cardDetail1:"/image/kampong thom/Phnom Santuk/pic1.jpg",
        cardDetail2:"/image/kampong thom/Phnom Santuk/pic2.jpg",
        cardDetail3:"/image/kampong thom/Phnom Santuk/pic3.jpg",
        cardDetail4:"/image/kampong thom/Phnom Santuk/pic4.jpg",
        cardDetail5:"/image/kampong thom/Phnom Santuk/pic5.jpg",
        Title:"Phnom Santuk",
        map:"https://www.google.com/search?q=map+from+phnom+penh+to+Phnom+Santuk&biw=1280&bih=569&sxsrf=ALiCzsZavQE7xnrvN8dAmME6zO8dcZmUbg%3A1671549826940&ei=gtOhY4boOPeTseMPvZ6giAw&ved=0ahUKEwiGsaKtwIj8AhX3SWwGHT0PCMEQ4dUDCA8&uact=5&oq=map+from+phnom+penh+to+Phnom+Santuk&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAEyBQghEKABOggIABCiBBCwAzoECCMQJzoGCAAQFhAeOgUIABCGA0oECEEYAUoECEYYAFC2A1itCmDWD2gBcAB4AIABeYgB8AGSAQMwLjKYAQCgAQGgAQLIAQTAAQE&sclient=gws-wiz-serp#",
        description2:"Stone Handicraft located at Ka Kos Village, Ka Kos Commune, Santhuk District in 16-km distance from Provincial Town of Kampong Thom on National Road 6. The craftsmen take the rocks from the Santhuk mountain’s foot to make statues and various figures for house decoration. This stone handicraft is served for domestically and internationally target markets. Beside stone handicraft, Kampong Thom has other handicraft like Krama, Silk shirts, traditional khmer clothing and handbags.",
    },
    {
        id:4,
        cardBlog:"/image/kampong thom/Wat Kuhak Nokor/Wat Kuhak Nokor.jpg",
        cardDetail1:"/image/kampong thom/Wat Kuhak Nokor/pic1.jpg",
        cardDetail2:"/image/kampong thom/Wat Kuhak Nokor/pic2.jpg",
        cardDetail3:"/image/kampong thom/Wat Kuhak Nokor/pic3.jpg",
        cardDetail4:"/image/kampong thom/Wat Kuhak Nokor/pic4.jpg",
        cardDetail5:"/image/kampong thom/Wat Kuhak Nokor/pic5.jpg",
        Title:" Kuhak Nokor",
        map:"https://www.google.com/search?q=map+from+phnom+penh+to+Wat+Kuhak+Nokor&biw=1280&bih=569&sxsrf=ALiCzsau_2qo2R8nFW8e5zJi08N_alk_fg%3A1671549769864&ei=SdOhY-euNPWMseMPlMyVoAg&ved=0ahUKEwin94aSwIj8AhV1RmwGHRRmBYQQ4dUDCA8&uact=5&oq=map+from+phnom+penh+to+Wat+Kuhak+Nokor&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQogQyBQgAEKIEMgUIABCiBDIFCAAQogQyBQgAEKIEOgoIABBHENYEELADSgQIQRgASgQIRhgAULsDWP8RYMseaAFwAXgAgAGZAYgB9QGSAQMxLjGYAQCgAQHIAQLAAQE&sclient=gws-wiz-serp#",
        description1:"Wat Kuhak Nokor is an eleventh-century site with a collection of laterite and sandstone buildings in a well-maintained 200 square meters park surrounded by a large sandstone rampart 3 meters in height. Built during the reign of King Suryavarman I, the style is similar to the Tonlé Bati temple.",
        description2:"Stone Handicraft located at Ka Kos Village, Ka Kos Commune, Santhuk District in 16-km distance from Provincial Town of Kampong Thom on National Road 6. The craftsmen take the rocks from the Santhuk mountain’s foot to make statues and various figures for house decoration. This stone handicraft is served for domestically and internationally target markets. Beside stone handicraft, Kampong Thom has other handicraft like Krama, Silk shirts, traditional khmer clothing and handbags.",
        howTogo:"7 km away from the mountain, sits a swimming spot at Popork Vil Waterfall. Tourists can swim and bathe here for pleasure.",
    },
    {
        id:5,
        cardBlog:"/image/kampong thom/Andet temple/Andet temple.jpg",
        cardDetail1:"/image/kampong thom/Andet temple/pic1.jpg",
        cardDetail2:"/image/kampong thom/Andet temple/pic2.jpg",
        cardDetail3:"/image/kampong thom/Andet temple/pic3.jpg",
        cardDetail4:"/image/kampong thom/Andet temple/pic4.jpg",
        cardDetail5:"/image/kampong thom/Andet temple/pic5.jpg",
        Title:"Andet temple",
        map:"https://www.google.com/search?q=map+from+phnom+penh+to+Sambo+Prei+Kuh+Temples&sxsrf=ALiCzsZdRGXMBMBKkJ8G7RD-SjmWbUrDOg%3A1671549593156&ei=mdKhY-30CN2YseMPxKq7wAM&ved=0ahUKEwitpeW9v4j8AhVdTGwGHUTVDjgQ4dUDCA8&uact=5&oq=map+from+phnom+penh+to+Sambo+Prei+Kuh+Temples&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQogQyBQgAEKIEOggIABCiBBCwAzoECCMQJzoGCAAQFhAeOgUIABCGA0oECEEYAUoECEYYAFC7D1j1FWCoJ2gCcAB4AIABmwGIAYcCkgEDMC4ymAEAoAEBoAECyAEDwAEB&sclient=gws-wiz-serp#",
        description1:"Andet temple, built in the Prei Kmeng style with one single brick tower, now nestles snugly alongside a modern Buddhist wat.  This was built in the latter part of the seventh century under Jayavarman I.",
        description2:"In the central group of temples, the decorative details of Prasat Tor (Lion temple) are similar in style to the ruins belonging to the period of king Jayavarman II of the ninth century.",
        
    },
    {
        id:6,
        cardBlog:"/image/kampong thom/Sambo Prei Kuh Temples/Sambo Prei Kuh Temples.jpg",
        cardDetail1:"/image/kampong thom/Sambo Prei Kuh Temples/pic1.jpg",
        cardDetail2:"/image/kampong thom/Sambo Prei Kuh Temples/pic2.jpg",
        cardDetail3:"/image/kampong thom/Sambo Prei Kuh Temples/pic3.jpg",
        cardDetail4:"/image/kampong thom/Sambo Prei Kuh Temples/pic4.jpg",
        cardDetail5:"/image/kampong thom/Sambo Prei Kuh Temples/pic5.jpg",
        Title:"Sambo Prei Kuh Temples",
        map:"https://www.google.com/search?q=map+from+phnom+penh+to+Sambo+Prei+Kuh+Temples&sxsrf=ALiCzsZdRGXMBMBKkJ8G7RD-SjmWbUrDOg%3A1671549593156&ei=mdKhY-30CN2YseMPxKq7wAM&ved=0ahUKEwitpeW9v4j8AhVdTGwGHUTVDjgQ4dUDCA8&uact=5&oq=map+from+phnom+penh+to+Sambo+Prei+Kuh+Temples&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQogQyBQgAEKIEOggIABCiBBCwAzoECCMQJzoGCAAQFhAeOgUIABCGA0oECEEYAUoECEYYAFC7D1j1FWCoJ2gCcAB4AIABmwGIAYcCkgEDMC4ymAEAoAEBoAECyAEDwAEB&sclient=gws-wiz-serp#",
        description1:"Founded by King Isanavarman I during the seventh century, Sambo Prei Kuh was once the capital of Chenla known as Isanapura, and was a religious center dedicated to the worship of Shiva.",
        description2:"Collectively, the complex consists of more than a hundred temples built of solid bricks, laterite and sandstone and from the remains. It is understood that several successions of kings have maintained this site as their capital, each time adding more temples and monuments to the capital city.",
       
        howTogo:"",
    },
    
    
]
